# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

TT_GS_sp <- function(n, R, nu, x, lower, upper) {
    .Call('TTmomentRcpp_TT_GS_sp', PACKAGE = 'TTmomentRcpp', n, R, nu, x, lower, upper)
}

